[example_rest_html]
name = "REST>HTML Example"

[example_rest_html.input]
type = "REST JSON"

[example_rest_html.input.settings]
URL = "https://official-joke-api.appspot.com/jokes/programming/random"
Type = "GET"

[example_rest_html.output]
type = "HTML"

[example_rest_xml]
name = "REST>XML"

[example_rest_xml.input]
type = "REST JSON"

[example_rest_xml.input.settings]
URL = "https://official-joke-api.appspot.com/jokes/programming/random"
Type = "GET"

[example_rest_xml.output]
type = "XML"

[example_rest_csv]
name = "REST>CSV"

[example_rest_csv.input]
type = "REST JSON"

[example_rest_csv.input.settings]
URL = "https://official-joke-api.appspot.com/jokes/programming/random"
Type = "GET"

[example_rest_csv.output]
type = "CSV"

[example_rest_yaml]
name = "REST>YAML"

[example_rest_yaml.input]
type = "REST JSON"

[example_rest_yaml.input.settings]
URL = "https://official-joke-api.appspot.com/jokes/programming/random"
Type = "GET"

[example_rest_yaml.output]
type = "YAML"

[example_rest_toml]
name = "REST>TOML"

[example_rest_toml.input]
type = "REST JSON"

[example_rest_toml.input.settings]
URL = "https://official-joke-api.appspot.com/jokes/programming/random"
Type = "GET"

[example_rest_toml.output]
type = "TOML"

[example_csv_html]
name = "CSV>HTML"

[example_csv_html.input]
type = "CSV"

[example_csv_html.input.settings]
Data = "John,Doe,120 jefferson st.,Riverside, NJ, 08075\r\nJack,McGinnis,220 hobo Av.,Phila, PA,09119\r\n\"John \"\"Da Man\"\"\",Repici,120 Jefferson St.,Riverside, NJ,08075\r\nStephen,Tyler,\"7452 Terrace \"\"At the Plaza\"\" road\",SomeTown,SD, 91234\r\n,Blankman,,SomeTown, SD, 00298\r\n\"Joan \"\"the bone\"\", Anne\",Jet,\"9th, at Terrace plc\",Desert City,CO,00123\r\n"

[example_csv_html.output]
type = "HTML"

[example_toml_to_yaml]
name = "TOML>YAML"

[example_toml_to_yaml.input]
type = "TOML"

[example_toml_to_yaml.input.settings]
Data = """
# This is a TOML document.

title = "TOML Example"

[owner]
name = "Tom Preston-Werner"
dob = 1979-05-27T07:32:00-08:00 # First class dates

[database]
server = "192.168.1.1"
ports = [ 8001, 8001, 8002 ]
connection_max = 5000
enabled = true

[servers]

  # Indentation (tabs and/or spaces) is allowed but not required
  [servers.alpha]
  ip = "10.0.0.1"
  dc = "eqdc10"

  [servers.beta]
  ip = "10.0.0.2"
  dc = "eqdc10"

[clients]
data = [ ["gamma", "delta"], [1, 2] ]

# Line breaks are OK when inside arrays
hosts = [
  "alpha",
  "omega"
]
"""

[example_toml_to_yaml.output]
type = "YAML"

[example_xml_html]
name = "XML>HTML Example"

[example_xml_html.input]
type = "XML"

[example_xml_html.input.settings]
Data = """
<!-- from https://github.com/FFY00/dbus-objects -->
<!DOCTYPE node PUBLIC
"-//freedesktop//DTD D-BUS Object Introspection 1.0//EN"
"http://www.freedesktop.org/standards/dbus/1.0/introspect.dtd" >
<node xmlns:doc="http://www.freedesktop.org/dbus/1.0/doc.dtd">
    <interface name="io.github.ffy00.dbus_objects.example.ExampleObject">
        <method name="GetBets">
            <arg direction="out" type="ai" />
        </method>
        <method name="Lotery">
            <arg direction="out" type="i" />
        </method>
        <method name="Ping">
            <arg direction="out" type="s" />
        </method>
        <method name="Print">
            <arg direction="in" type="s" name="msg" />
        </method>
        <method name="SaveBet">
            <arg direction="in" type="i" name="number" />
        </method>
        <method name="Sum">
            <arg direction="in" type="i" name="a" />
            <arg direction="in" type="i" name="b" />
            <arg direction="out" type="i" />
        </method>
    </interface>
    <interface name="org.freedesktop.DBus.Properties">
        <method name="GetAll">
            <arg direction="in" type="s" name="interface_name" />
            <arg direction="out" type="a{sv}" />
        </method>
    </interface>
    <interface name="org.freedesktop.DBus.Introspectable">
        <method name="Introspect">
            <arg direction="out" type="s" name="xml" />
        </method>
    </interface>
    <interface name="org.freedesktop.DBus.Peer">
        <method name="Ping" />
    </interface>
</node>
"""

[example_xml_html.output]
type = "HTML"
