[example_xml_html]
name = "XML>HTML Example"

[example_xml_html.input]
type = "XML"

[example_xml_html.input.settings]
Data = "\n                <interface name=\"org.freedesktop.DBus.Properties\">\n                    <method name=\"GetAll\">\n                        <arg direction=\"in\" type=\"s\" name=\"interface_name\" />\n                        <arg direction=\"out\" type=\"a{sv}\" />\n                    </method>\n                </interface>\n            "

[example_xml_html.output]
type = "HTML"

[example_rest_html]
name = "REST>HTML Example"

[example_rest_html.input]
type = "REST JSON"

[example_rest_html.input.settings]
URL = "https://official-joke-api.appspot.com/jokes/programming/random"
Type = "GET"

[example_rest_html.output]
type = "HTML"

[example_rest_xml]
name = "REST>XML"

[example_rest_xml.input]
type = "REST JSON"

[example_rest_xml.input.settings]
URL = "https://official-joke-api.appspot.com/jokes/programming/random"
Type = "GET"

[example_rest_xml.output]
type = "XML"

[example_rest_csv]
name = "REST>CSV"

[example_rest_csv.input]
type = "REST JSON"

[example_rest_csv.input.settings]
URL = "https://official-joke-api.appspot.com/jokes/programming/random"
Type = "GET"

[example_rest_csv.output]
type = "CSV"

[example_rest_yaml]
name = "REST>YAML"

[example_rest_yaml.input]
type = "REST JSON"

[example_rest_yaml.input.settings]
URL = "https://official-joke-api.appspot.com/jokes/programming/random"
Type = "GET"

[example_rest_yaml.output]
type = "YAML"

[example_toml_to_yaml]
name = "YAML>TOML"

[example_toml_to_yaml.input]
type = "TOML"

[example_toml_to_yaml.input.settings]
Data = """
# This is a TOML document.

title = "TOML Example"

[owner]
name = "Tom Preston-Werner"
dob = 1979-05-27T07:32:00-08:00 # First class dates

[database]
server = "192.168.1.1"
ports = [ 8001, 8001, 8002 ]
connection_max = 5000
enabled = true

[servers]

  # Indentation (tabs and/or spaces) is allowed but not required
  [servers.alpha]
  ip = "10.0.0.1"
  dc = "eqdc10"

  [servers.beta]
  ip = "10.0.0.2"
  dc = "eqdc10"

[clients]
data = [ ["gamma", "delta"], [1, 2] ]

# Line breaks are OK when inside arrays
hosts = [
  "alpha",
  "omega"
]
"""

[example_toml_to_yaml.output]
type = "YAML"

[examplerest_rest]
name = "REST>REST Example"

[examplerest_rest.input]
type = "REST JSON"

[examplerest_rest.input.settings]
URL = "https://official-joke-api.appspot.com/jokes/programming/random"
Type = "GET"

[examplerest_rest.output]
type = "REST JSON"
